### ISSUE TITLE
Support Safari

### ISSUE THREAD

**Issue by domoritz** [domoritz/arrow-wasm#9]
Right now, we get `arrow = ReferenceError: Can't find variable: BigInt64Array`.

**Comment by marcprux** [comment]
The problem is described (and fixed) at: https://github.com/apache/arrow/pull/9110. The issue is that recent versions of JavaScriptCore/WebKit in Safari support BigInt but do not support `BigInt64Array`, and so anything that relies on `BigInt64Array` will fail despite `BigIntAvailable` being true

Until this PR is merged and release, this can be worked-around by patching the Arrow source, as I did at: https://github.com/glimpseio/glimpseviz/blob/3e9d936bdf157bc9034e7b5669fca3efa27eb510/package.json#L35

**Comment by marcprux** [comment]
The problem is actually this: https://bugs.webkit.org/show_bug.cgi?id=190800

The comment above is the report & workaround for the *TypeScript/Arrow* implementation; Rust/WASM/Arrow version just happens to hit the same Safari/WebKit limitation, and so the error message is the same. 

I don't know if there is any viable workaround for this aside from some polyfill-based solution to simulate `BigInt64Array`

**Comment by marcprux** [comment]
A fix was pushed to WebKit last week: https://trac.webkit.org/changeset/272170/webkit. 

It was implemented by an Apple engineer, so there may be cause to hope that the feature will make it into WebKit on macOS & iOS sometime soon.

**Comment by domoritz** [comment]
Great. I don't think we need to do anything here then and wait for the release.
